---
- name: test playbook
  hosts: all
  tasks:
    - name: get hostname
      win_shell: Get-WmiObject Win32_ComputerSystem
    - name: Send mail
      community.general.mail:
        subject: Test subject
      delegate_to: localhost
      
