---
- name: test playbook
  hosts: dc01.winadmin.me
  tasks:
    - name: get ComputerSystem
      win_shell: Get-WmiObject Win32_ComputerSystem
      register: cs
    - name: Debug
      debug:
        msg: "{{ cs.stdout_lines }}"
    - name: Debug
      debug:
        msg: "{{ ansible_facts }}"
